name: 'Dev Pipeline'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install Salesforce CLI
        run: |
          git log --oneline
          #git rev-parse HEAD
          git rev-parse HEAD^ > headcommit
          echo "$headcommit"

          
        
        

