name: 'UAT'

on: 
  workflow_dispatch:
    inputs:
        environment:
          description: 'Define env name'     
          required: true
          default: 'prod'
  #push:
  pull_request:
    branches:
      - UAT

jobs:
  build_test_deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Write the token into a file
        run: 'echo ${{ secrets.UAT_TOKEN}} > uattoken.txt'
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
          sfdx --version
          sfdx plugins --core
          sudo apt-get install -y jq
      - name: Install vlocityestools
        run: 'echo y | sfdx plugins:install vlocityestools'
      - name: Auth with the DevHub
        run: 'sfdx force:auth:sfdxurl:store -f uattoken.txt -a ${{secrets.UAT_ALIAS}} -d'
      - name: Dev hub connection verify
        run: 'sfdx force:org:list'
      - name: verify and deploy delta changes
        run: |
          echo $GITHUB_SHA
          head_commit=$(git rev-parse HEAD^)
          echo $head_commit
          if [ -d force-app_delta ]; then
          rm -rf force-app_delta
          fi
          #echo "---- Validating delta package  ----"
          echo y | sfdx vlocityestools:sfsource:createdeltapackagelocal -h $head_commit -d force-app
          #sfdx force:source:deploy --sourcepath force-app_delta -u ${{secrets.DEMO_ALIAS}} --verbose --checkonly
          #sfdx force:apex:test:run --wait 10 --resultformat human --codecoverage --testlevel RunLocalTests -u ${{secrets.DEMO_ALIAS}}
          #sfdx force:apex:test:run --wait 10 -n Woil_CustomerTrigger_handler -r human -u ${{secrets.DEMO_ALIAS}}
          #git config user.name github-actions
          #git config user.email github-actions@github.com
          #git add force-app_delta
          #git commit -m "force-app_delta"
          #git push
